name: webview_app
description: "Un nouveau projet Flutter."
# La ligne suivante empêche la publication accidentelle du package sur
# pub.dev via `flutter pub publish`. C'est préférable pour les packages privés.
publish_to: 'none' # Retirez cette ligne si vous souhaitez publier sur pub.dev

# La ligne suivante définit la version et le numéro de build de votre application.
# Un numéro de version est composé de trois chiffres séparés par des points, comme 1.2.43,
# suivi d'un numéro de build optionnel séparé par un +.
# En Android, le numéro de version est utilisé comme `versionName` tandis que le numéro de build est utilisé comme `versionCode`.
# Lisez plus sur la gestion des versions Android ici : https://developer.android.com/studio/publish/versioning
# En iOS, le numéro de version est utilisé comme `CFBundleShortVersionString` et le numéro de build comme `CFBundleVersion`.
# Lisez plus sur la gestion des versions iOS ici :
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# En Windows, `build-name` est utilisé pour les parties majeures, mineures et de patch
# de la version du produit et du fichier, tandis que `build-number` est utilisé pour le suffixe de build.
# version: 1.0.0+1

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: 4.10.0 # Ou toute version compatible
  shared_preferences: ^2.0.0
  firebase_core: ^3.12.1
  flutter_inappwebview: ^6.1.5   

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  # Cette ligne garantit que la police des icônes Material est incluse
  # dans votre application, vous permettant d'utiliser les icônes de la classe Material Icons.
  uses-material-design: true

  # Pour ajouter des ressources à votre application, ajoutez une section assets, comme ceci :
  assets:
    - assets/logo_managtech.png  # Assure-toi que l'indentation est correcte ici

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_managtech.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_managtech.png"  